/**
 * Generates the provider model catalogs under `src/pi-ai/providers/*.models.ts`
 * (plus the `src/pi-ai/models.generated.ts` aggregate) from the JSON data
 * assets in `src/pi-ai/providers/data/*.models.json`.
 *
 * The JSON files are the source of truth: they are plain data assets that can
 * be refreshed from upstream provider catalogs without touching code, which
 * keeps model-catalog churn out of hand-written TypeScript.
 *
 * Usage:
 *   npm run generate-models         # rewrite the generated TypeScript
 *   npm run generate-models:check   # fail if the checked-in output is stale
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const PROVIDERS_DIR = path.resolve("src/pi-ai/providers");
const DATA_DIR = path.join(PROVIDERS_DIR, "data");
const AGGREGATE_FILE = path.resolve("src/pi-ai/models.generated.ts");

const HEADER = [
  "// This file is auto-generated by scripts/generate-models.ts",
  "// Do not edit manually - run 'npm run generate-models' to update",
  "",
];

/** Keys emitted as expanded multi-line objects rather than inline JSON. */
const EXPANDED_OBJECT_KEYS = new Set(["cost"]);
/** Keys inside an expanded object that stay inline JSON (arrays of records). */
const INLINE_NESTED_KEYS = new Set(["tiers"]);

type ModelRecord = Record<string, unknown>;
type CatalogJson = Record<string, ModelRecord>;

function constNameFor(slug: string): string {
  return `${slug.replace(/-/g, "_").toUpperCase()}_MODELS`;
}

function providerSlugs(): string[] {
  return readdirSync(DATA_DIR)
    .filter((file) => file.endsWith(".models.json"))
    .map((file) => file.replace(/\.models\.json$/, ""))
    .sort();
}

function readCatalog(slug: string): CatalogJson {
  const file = path.join(DATA_DIR, `${slug}.models.json`);
  return JSON.parse(readFileSync(file, "utf8")) as CatalogJson;
}

function renderStringArray(values: unknown[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}

function renderValue(key: string, value: unknown, indent: string): string {
  if (Array.isArray(value)) return renderStringArray(value);
  if (value !== null && typeof value === "object" && EXPANDED_OBJECT_KEYS.has(key)) {
    const inner = Object.entries(value as ModelRecord)
      .map(([nestedKey, nestedValue]) => {
        const rendered = INLINE_NESTED_KEYS.has(nestedKey)
          ? JSON.stringify(nestedValue)
          : JSON.stringify(nestedValue);
        return `${indent}\t${nestedKey}: ${rendered},`;
      })
      .join("\n");
    return `{\n${inner}\n${indent}}`;
  }
  return JSON.stringify(value);
}

function renderModel(id: string, model: ModelRecord): string {
  const lines: string[] = [`\t${JSON.stringify(id)}: {`];
  for (const [key, value] of Object.entries(model)) {
    if (value === undefined) continue;
    lines.push(`\t\t${key}: ${renderValue(key, value, "\t\t")},`);
  }
  const api = JSON.stringify(model.api);
  lines.push(`\t} satisfies Model<${api}>,`);
  return lines.join("\n");
}

function renderCatalogModule(slug: string, catalog: CatalogJson): string {
  const body = Object.entries(catalog)
    .map(([id, model]) => renderModel(id, model))
    .join("\n");
  return [
    ...HEADER,
    'import type { Model } from "../types.ts";',
    "",
    `export const ${constNameFor(slug)} = {`,
    body,
    "} as const;",
    "",
  ].join("\n");
}

function renderAggregateModule(slugs: string[]): string {
  const imports = slugs.map(
    (slug) => `import { ${constNameFor(slug)} } from "./providers/${slug}.models.ts";`,
  );
  const entries = slugs.map((slug) => `\t${JSON.stringify(slug)}: ${constNameFor(slug)},`);
  return [
    ...HEADER,
    ...imports,
    "",
    "export const MODELS = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const slugs = providerSlugs();
  const outputs = new Map<string, string>();

  for (const slug of slugs) {
    outputs.set(
      path.join(PROVIDERS_DIR, `${slug}.models.ts`),
      renderCatalogModule(slug, readCatalog(slug)),
    );
  }
  outputs.set(AGGREGATE_FILE, renderAggregateModule(slugs));

  const stale: string[] = [];
  for (const [file, content] of outputs) {
    let current: string | undefined;
    try {
      current = readFileSync(file, "utf8");
    } catch {
      current = undefined;
    }
    if (current === content) continue;
    if (check) {
      stale.push(path.relative(process.cwd(), file));
      continue;
    }
    writeFileSync(file, content);
  }

  if (check) {
    if (stale.length > 0) {
      console.error("Generated model catalogs are out of date:");
      for (const file of stale) console.error(`  ${file}`);
      console.error("Run 'npm run generate-models' and commit the result.");
      process.exit(1);
    }
    console.log(`Model catalogs up to date (${slugs.length} providers).`);
    return;
  }

  const modelCount = slugs.reduce((total, slug) => total + Object.keys(readCatalog(slug)).length, 0);
  console.log(`Generated ${slugs.length} provider catalogs (${modelCount} models).`);
}

main();
